# Welcome to Jekyll!
#

# Site settings
title: Reylam
description: Reylam est un rappeur français 
owner: reylam.org # or company name
first_published: 201 # if migrating another site, the year of your first publish
email: reylam@gmx.fr
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://reylam.org" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
social:


  # linkedin-square: https://www.linkedin.com/company/astral-dynamics-cyf
  facebook-official: https://www.facebook.com/reylam
  twitter: https://twitter.com/reylam
  #ngoogle-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/reylam
  #github: https://github.com/reylam
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
